import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "..");
const t = JSON.parse(fs.readFileSync(path.join(here, "topology.json"), "utf8"));
const directPin = "511abec23ce83344abdc2686e313cc1dfc8de3e3";
const contractPin = "ce6de94e585637b9f3c370b6e917d74e6bb08a7e";
const bindings = {"web-server":["customer-auth","SUPABASE_AUTH_DATABASE_URL","NEON_AUTH_DATABASE_URL"],"api-server":["customer-auth","SUPABASE_AUTH_DATABASE_URL","NEON_AUTH_DATABASE_URL"],"admin-web-server":["admin-auth","SUPABASE_ADMIN_DATABASE_URL","NEON_ADMIN_DATABASE_URL"],"admin-api-server":["admin-auth","SUPABASE_ADMIN_DATABASE_URL","NEON_ADMIN_DATABASE_URL"]};
const ok = (value, message) => { if (!value) throw new Error(message); };
const clean = (value, label) => { const text = typeof value === "string" ? value : JSON.stringify(value); ok(!/postgres(?:ql)?:\/\//i.test(text), `${label}: database URL committed`); ok(!/BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY/i.test(text), `${label}: private key committed`); ok(!/eyJ[\w-]{10,}\.[\w-]{10,}\./.test(text), `${label}: bearer/JWT material committed`); };
ok(t.contract === "SharedAuthTopology" && t.version === 2 && t.linearIssue === "DEN-2843" && t.runtimeState === "source-only", "wrong topology contract/state");
ok(t.contractSource?.repository === "shared-auth/shared-auth-infra" && t.contractSource?.commit === contractPin && t.contractSource?.path === "scripts/validate-shared-auth-runtime-contract.mjs", "wrong contract source");
for (const [name, provider, customerKey, adminKey] of [["Supabase",t.supabase,"SUPABASE_AUTH_DATABASE_URL","SUPABASE_ADMIN_DATABASE_URL"],["Neon",t.neon,"NEON_AUTH_DATABASE_URL","NEON_ADMIN_DATABASE_URL"]]) { ok(provider?.runtimeOrg === t.githubOrg && provider?.targetOrg === t.githubOrg, `${name} organization mismatch`); ok(provider?.placement === "dedicated-org" && provider?.transition === null, `${name} must be dedicated without waiver`); ok(provider?.authDatabaseUrlEnv === customerKey && provider?.adminDatabaseUrlEnv === adminKey, `${name} database keys invalid`); }
const p=t.requestPolicy; ok(p.requireBothProvidersConfigured===true&&p.startupMode==="strict-paired-config","both providers required"); ok(["availability-first","strict-paired"].includes(p.customerMode),"invalid customer mode"); ok(p.adminMode==="strict-paired"&&p.sensitiveMode==="strict-paired"&&p.providerDisagreement==="deny","strict policy missing");
ok(Object.keys(t.roleBindings??{}).sort().join()===Object.keys(bindings).sort().join(),"four bindings required"); ok(Object.keys(t.roleIntegrations??{}).sort().join()===Object.keys(bindings).sort().join(),"four integrations required");
for(const [role,[realm,supabaseKey,neonKey]] of Object.entries(bindings)){const b=t.roleBindings[role];ok(b.realm===realm&&b.supabaseDatabaseUrlEnv===supabaseKey&&b.neonDatabaseUrlEnv===neonKey,`${role}: wrong binding`);const i=t.roleIntegrations[role];ok(i.repository.startsWith(`${t.githubOrg}/`)&&["direct","ores-middleware"].includes(i.target)&&["blocked","piloting"].includes(i.status),`${role}: invalid integration`);ok(i.authority==="github.com/shared-auth"&&i.singleDecisionPath===true&&i.allowProviderTokensAtApplicationBoundary===false&&i.allowProductLocalHumanVerifier===false,`${role}: split authority`);ok(Object.values(i.evidence??{}).every((value)=>value===null||value===false),`${role}: evidence overclaimed`);if(i.target==="direct"){ok(i.clientPackage==="shared-auth-service-client"&&i.immutableClientPin===directPin&&i.middlewareAuthVerifier===null&&i.immutableAdapterPin===null,`${role}: direct path invalid`)}else{ok(i.clientPackage===null&&i.immutableClientPin===null&&i.middlewareAuthVerifier==="shared-auth"&&i.rejectAnonymousDefault===true&&/^[0-9a-f]{40}$/.test(i.immutableAdapterPin),`${role}: middleware path invalid`)}}
ok(Array.isArray(t.auditRepositories)&&t.auditRepositories.length===5&&new Set(t.auditRepositories).size===5&&t.auditRepositories.every((repo)=>repo.startsWith(`${t.githubOrg}/`)),"invalid audit repository set");const audited=new Set(t.auditRepositories);for(const finding of t.findings??[]){ok(["high","critical"].includes(finding.severity)&&finding.status==="open"&&audited.has(finding.repository)&&finding.detail?.length>=40,`invalid finding: ${finding.code}`)}for(const i of Object.values(t.roleIntegrations)){if(i.status==="blocked")ok((t.findings??[]).some((finding)=>finding.repository===i.repository),`blocked repo lacks finding: ${i.repository}`)}
for(const [provider,realm,key,file] of [["supabase","customer-auth","SUPABASE_AUTH_DATABASE_URL","supabase/auth/migrations/202609070001_shared_auth_runtime_policy.sql"],["supabase","admin-auth","SUPABASE_ADMIN_DATABASE_URL","supabase/admin/migrations/202609070001_shared_auth_runtime_policy.sql"],["neon","customer-auth","NEON_AUTH_DATABASE_URL","neon/auth/migrations/202609070001_shared_auth_runtime_policy.sql"],["neon","admin-auth","NEON_ADMIN_DATABASE_URL","neon/admin/migrations/202609070001_shared_auth_runtime_policy.sql"]]){const sql=fs.readFileSync(path.join(root,file),"utf8");for(const literal of [t.githubOrg,provider,realm,key])ok(sql.includes(`'${literal}'`),`${file}: missing ${literal}`);ok(/enable row level security/i.test(sql)&&/revoke all/i.test(sql)&&/on conflict \(singleton\)/i.test(sql),`${file}: access/reconciliation hardening missing`);clean(sql,file)}clean(t,"topology");ok(!/shared-org-schema/i.test(JSON.stringify(t)),"shared provider placement forbidden");console.log(`validated fail-closed Shared Auth topology for ${t.githubOrg}`);
