apiVersion: apps/v1
kind: Deployment
metadata:
  name: declmig-api-server
  namespace: declmig
spec:
  replicas: 2
  selector:
    matchLabels:
      app: declmig-api-server
  template:
    metadata:
      labels:
        app: declmig-api-server
    spec:
      containers:
        - name: api
          image: ghcr.io/declarative-migrations/declmig-api-server.rs:main
          ports:
            - containerPort: 8080
          env:
            - name: DECLMIG_API_BIND
              value: "0.0.0.0:8080"

